Repository techInterview-study/Tech_Interview_for_Beginner, pull requests merged in 2024-04, with the labels that each got.

#61 [성환] Computer & OS 내용 정리
  OS/img/os_computer_and_os_1.png
  OS/os_computer_and_os.md
Labels: 🔗operating system

#62 [효림] Cookie&Session 내용 작성
  Network/img/network_cookie.png
  Network/img/network_session.jpg
  Network/network_cookie_session.md
Labels: 👾 network

#60 [혜윤] 네트워크 토폴로지 내용 정리
  Network/img/network_topology_1.png
  Network/img/network_topology_2.png
  Network/img/network_topology_3.png
  Network/img/network_topology_4.png
  Network/img/network_topology_5.png
  Network/img/network_topology_6.png
  Network/network_topology.md
Labels: 👾 network

#59 [예진] REST_API & RESTFUL 내용 정리
  Network/img/network_rest_api&restful_1.png
  Network/img/network_rest_api&restful_10.png
  Network/img/network_rest_api&restful_2.png
  Network/img/network_rest_api&restful_3.png
  Network/img/network_rest_api&restful_4.png
  Network/img/network_rest_api&restful_6.png
  Network/img/network_rest_api&restful_7.png
  Network/img/network_rest_api&restful_8.png
  Network/img/network_rest_api&restful_9.png
  Network/network_l4_l7_switch&loadbalancing.md
  Network/network_rest_api&restful.md
Labels: 👾 network

#58 [재성] Network sop and cors 내용 정리
  Network/img/network_sop_cors_1.png
  Network/img/network_sop_cors_2.png
  Network/img/network_sop_cors_3.png
  Network/img/network_sop_cors_4.png
  Network/network_sop_cors.md
Labels: 👾 network

#57 [윤하] proxy server 내용 작성
  Network/img/network_proxy_server_1.png
  Network/img/network_proxy_server_2.png
  Network/img/network_proxy_server_3.png
  Network/network_proxy_server.md
Labels: 👾 network

#56 [치왕] HTTPS 내용 작성
  Network/img/network_https_1.jpg
  Network/img/network_https_2.png
  Network/img/network_https_3.png
  Network/img/network_https_4.png
  Network/img/network_https_5.png
  Network/network_bandwidth.md
  Network/network_https.md
Labels: 👾 network

#65 [치왕] README 파일 연결 및 네트워크 인터뷰 - 1 업로드
  Interview/IV_Network/README.md
  Interview/IV_Network/iv_basic.md
  Network/README.md
  Network/network_https.md
  README.md
Labels: 📔 documentation, 👾 network

#66 [치왕] os Memory Hierachy 내용 작성
  OS/img/os_memory_hierarchy_1.png
  OS/img/os_memory_hierarchy_2.png
  OS/img/os_memory_hierarchy_3.png
  OS/img/os_memory_hierarchy_4.png
  OS/os_memory_hierarchy.md
  README.md
Labels: 🔗operating system

#69 [윤하] cpu scheduling and algorithm 내용 작성
  OS/img/os_cpu_scheduling_and_algorithm_1.PNG
  OS/img/os_cpu_scheduling_and_algorithm_2.PNG
  OS/img/os_cpu_scheduling_and_algorithm_3.PNG
  OS/img/os_cpu_scheduling_and_algorithm_4.PNG
  OS/img/os_cpu_scheduling_and_algorithm_5.PNG
  OS/img/os_cpu_scheduling_and_algorithm_6.PNG
  OS/img/os_cpu_scheduling_and_algorithm_7.PNG
  OS/img/os_cpu_scheduling_and_algorithm_8.PNG
  OS/os_cpu_scheduling_and_algorithm.md
Labels: 🔗operating system

#70 [재성] interrupt 내용 정리
  OS/img/os_interrupt_1.png
  OS/img/os_interrupt_2.png
  OS/os_interrupt.md
Labels: 🔗operating system

#72 [효림] process and thread 내용 정리
  OS/img/os_process_thread_context.PNG
  OS/img/os_process_thread_difference.PNG
  OS/img/os_process_thread_fork_exec.PNG
  OS/img/os_process_thread_kernel.PNG
  OS/img/os_process_thread_memory.PNG
  OS/img/os_process_thread_multithread.PNG
  OS/img/os_process_thread_multithread_error.PNG
  OS/img/os_process_thread_pbc.PNG
  OS/img/os_process_thread_pid.PNG
  OS/img/os_process_thread_process.PNG
  OS/img/os_process_thread_process_hierarcy.PNG
  OS/img/os_process_thread_process_state_diagram.PNG
  OS/img/os_process_thread_thread1.PNG
  OS/img/os_process_thread_thread2.PNG
  OS/img/os_process_thread_thread3.PNG
  OS/os_process&thread.md
Labels: 🔗operating system

#74 [혜윤] os system call 내용 정리
  OS/img/os_system_call_1.png
  OS/img/os_system_call_10.png
  OS/img/os_system_call_11.png
  OS/img/os_system_call_2.png
  OS/img/os_system_call_3.png
  OS/img/os_system_call_4.png
  OS/img/os_system_call_5.png
  OS/img/os_system_call_6.png
  OS/img/os_system_call_7.png
  OS/img/os_system_call_8.png
  OS/img/os_system_call_9.png
  OS/os_system_call.md
Labels: 🔗operating system

#75 [예진] PCB & Context Switching 내용 정리
  OS/img/os_pcb_and_context_switching_1.png
  OS/img/os_pcb_and_context_switching_2.png
  OS/img/os_pcb_and_context_switching_3.png
  OS/os_pcb_and_context_switching.md
Labels: 🔗operating system

#76 [성환] Address Space and Virtual Memory 내용 작성
  OS/img/os_adress_space_and_virtual_memory_1.png
  OS/img/os_adress_space_and_virtual_memory_2.png
  OS/img/os_adress_space_and_virtual_memory_3.png
  OS/img/os_adress_space_and_virtual_memory_4.png
  OS/img/os_adress_space_and_virtual_memory_5.png
  OS/img/os_adress_space_and_virtual_memory_6.jpg
  OS/os_adress_space_and_virtual_memory.md
Labels: 🔗operating system

#79 [예진] 스핀락, 뮤텍스, 세마포어 내용 정리
  OS/img/os_spin_lock_and_mutex_and_semaphore_1.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_10.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_11.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_12.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_13.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_14.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_15.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_16.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_17.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_18.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_19.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_2.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_20.png
  OS/img/os_spin_lock_and_mutex_and_semaphore_21.png
  OS/img/os_spin_lock_and_mutex_and_semaphore_3.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_4.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_5.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_6.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_7.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_8.jpg
  OS/img/os_spin_lock_and_mutex_and_semaphore_9.jpg
  OS/os_spin_lock_and_mutex_and_semaphore.md
Labels: 🔗operating system

#81 [성환] DeadLock 내용 정리
  OS/img/os_deadlock_1.png
  OS/img/os_deadlock_2.png
  OS/img/os_deadlock_3.png
  OS/os_deadlock.md
Labels: 🔗operating system

#84 [효림] paging 내용정리
  OS/img/os_paging.md
  OS/img/os_paging_0.PNG
  OS/img/os_paging_address.PNG
  OS/img/os_paging_address_trans.png
  OS/img/os_paging_definition.PNG
  OS/img/os_paging_definition1.png
  OS/img/os_paging_definition2.PNG
  OS/img/os_paging_externalfragmentation.PNG
  OS/img/os_paging_internal.PNG
  OS/img/os_paging_last.png
  OS/img/os_paging_pagetable1.PNG
  OS/img/os_paging_pagetable2.PNG
  OS/img/os_paging_pagetableentry.PNG
  OS/img/os_paging_ptbr.PNG
  OS/img/os_paging_ptbr2.PNG
  OS/img/os_paging_pte.PNG
  OS/img/os_paging_ready1.PNG
  OS/img/os_paging_swapinout.PNG
  OS/img/os_paging_swapinout2.PNG
  OS/img/os_paging_tlb.PNG
  OS/img/os_paging_tlbhitmiss.PNG
  OS/os_paging.md
Labels: 🔗operating system

#83 [윤하] virtual memory and demand paging 내용 정리
  OS/img/os_virtual_memory_and_demand_paging_1.PNG
  OS/img/os_virtual_memory_and_demand_paging_2.PNG
  OS/img/os_virtual_memory_and_demand_paging_3.PNG
  OS/img/os_virtual_memory_and_demand_paging_4.PNG
  OS/os_virtual_memory_and_demand_paging.md
Labels: 🔗operating system
